app:
  channel: ${APP_CHANNEL:CANAL XPTO}

server:
  port: ${SERVER_PORT:9099}

logging:
  level:
    root: info
    #'[org.springframework.web]': ERROR
    #'[br.com.k3t.mvc.oauth]': TRACE
    '[org.springframework.security]': DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:channel-a}
            client-secret: dDoAclRfmKoq5Ba4MIPPBYLm95YTprZl
            #authorization-grant-type: authorization_code
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - address
        provider:
          keycloak:
            #authorization-uri: http://localhost:7080/realms/bootcamp-realm/protocol/openid-connect/auth
            #jwk-set-uri: http://keycloak:8080/realms/bootcamp-realm/protocol/openid-connect/certs
            #token-uri: http://keycloak:8080/realms/bootcamp-realm/protocol/openid-connect/token
            #user-info-uri: http://keycloak:8080/realms/bootcamp-realm/protocol/openid-connect/userinfo
            #user-name-attribute: preferred_username

            issuer-uri: ${ISSUER_URI:http://localhost:7080/realms/bootcamp-realm}
            #authorization-uri: http://localhost:7080/realms/bootcamp-realm/protocol/openid-connect/auth
            #jwk-set-uri: http://localhost:7080/realms/bootcamp-realm/protocol/openid-connect/certs
            #token-uri: http://localhost:7080/realms/bootcamp-realm/protocol/openid-connect/token
            #user-info-uri: http://localhost:7080/realms/bootcamp-realm/protocol/openid-connect/userinfo
            