server:
  port: ${SERVER_PORT:8083}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:channel-cih}
            client-secret: dDoAclRfmKoq5Ba4MIPPBYLm95YTprZl
            scope:
              - openid
              - profile
              - email
              - address
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:7080/realms/bootcamp-realm}
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:7080/realms/bootcamp-realm}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/bootcamp}
    username: bootcamp
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:7080}
  realm: bootcamp-realm
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin

app:
  channel: Customer Identity HUB

#logging:
#  level:
#    '[org.springframework.security]': DEBUG
#    '[org.springframework.web]': DEBUG