server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/bootcamp-realm
  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: bootcamp
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  url: http://localhost:7080
  realm: bootcamp-realm
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
